apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 80        # Service port (what clients connect to)
      targetPort: 5000 # Container port (your app listens on)
      nodePort: 30080  # Optional: fixed NodePort (range 30000–32767)